### ISSUE TITLE
Unable to discover/pair Nuimo on RPi3

### ISSUE THREAD

**Issue by mwild1** [riker09/Nuimo-MQTT-Bridge#2]
Hey, thanks for working on this!

I initially had some trouble installing the add-on, I made #1 with some changes.

What platform were you testing on?

The add-on starts and connects to MQTT successfully, but that's it. My Nuimo stays in bluetooth pairing mode, but nothing else happens. Am I missing something?

**Comment by riker09** [comment]
Well, you've got me. 😅 

I never found the time to get this working inside a Docker container on my RPi3. It only worked on my computer, running in Debug mode on Visual Studio Code. My OS is ElementaryOS 0.4 Loki.

I have installed the Docker container which enables BT support on a RPi3. My guess is, that this Nuimo container needs access to the BT peripheral as well. There are some strategies that might be worth an investigation:

1. Run the Nuimo container in privileged mode
2. Map the BT devices to the Nuimo container
3. Link the BT container to the Nuimo container

The first feels like brute force to me. And since I don't trust my own code probably not a good idea in terms of security. The second is effectivly the same, without exposing the docker host completely. The third solution would require that the BT container provides some sort of (native) API.

I currently don't have the time at my hands to investigate this further. Right now I have it running on my computer which is powered on all the time anyways. So this works for me. 🙈 

Of course I would be glad if someone could get this to work inside a Hass.io Docker container. I'll try to respond to any questions as quickly as possible.

**Comment by mwild1** [comment]
Ok, you're right, I got it working fine on my laptop. I've tried various things on the Pi, including running the container with privileges, but no luck so far. I'll keep digging.

**Comment by riker09** [comment]
I guess one way could be to clone the official Bluetooth support container and maybe enhance it with the code in this repo? Total shot in the dark, though.

**Comment by mwild1** [comment]
I got it working on the Pi. Just need to tidy up some stuff and submit a PR :)

**Comment by riker09** [comment]
Awesome! I'll check it tonight.
